src/Entity/Command.php
<?php

namespace App\Entity;

use App\Repository\AssocRepository;
use App\Repository\MenuRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandRepository")
 */
class Command
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="commands")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commandassoc", mappedBy="command", orphanRemoval=true)
     */
    private $commandassocs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commandmenu", mappedBy="command", orphanRemoval=true)
     */
    private $commandmenus;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Time")
     * @ORM\JoinColumn(nullable=true)
     */
    private $time;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\State")
     * @ORM\JoinColumn(nullable=false)
     */
    private $state;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datetime;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $totalPrice;

    public function __construct()
    {
        $this->commandassocs = new ArrayCollection();
        $this->commandmenus = new ArrayCollection();
        $this->datetime = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Commandassoc[]
     */
    public function getCommandassocs(): Collection
    {
        return $this->commandassocs;
    }

    public function addCommandassoc(Commandassoc $commandassoc): self
    {
        if (!$this->commandassocs->contains($commandassoc)) {
            $this->commandassocs[] = $commandassoc;
            $commandassoc->setCommand($this);
        }

        return $this;
    }

    public function removeCommandassoc(Commandassoc $commandassoc): self
    {
        if ($this->commandassocs->contains($commandassoc)) {
            $this->commandassocs->removeElement($commandassoc);
            // set the owning side to null (unless already changed)
            if ($commandassoc->getCommand() === $this) {
                $commandassoc->setCommand(null);
            }
        }

        return $this;
    }

    public function getDatetime(): ?\DateTimeInterface
    {
        return $this->datetime;
    }

    public function setDatetime(\DateTimeInterface $datetime): self
    {
        $this->datetime = $datetime;

        return $this;
    }
    /**
     * @return Collection|Commandmenu[]
     */
    public function getCommandmenus(): Collection
    {
        return $this->commandmenus;
    }

    public function addCommandmenu(Commandmenu $commandmenu): self
    {
        if (!$this->commandmenus->contains($commandmenu)) {
            $this->commandmenus[] = $commandmenu;
            $commandmenu->setCommand($this);
        }

        return $this;
    }

    public function removeCommandmenu(Commandmenu $commandmenu): self
    {
        if ($this->commandmenus->contains($commandmenu)) {
            $this->commandmenus->removeElement($commandmenu);
            // set the owning side to null (unless already changed)
            if ($commandmenu->getCommand() === $this) {
                $commandmenu->setCommand(null);
            }
        }

        return $this;
    }

    public function getTime(): ?Time
    {
        return $this->time;
    }

    public function setTime(?Time $time): self
    {
        $this->time = $time;

        return $this;
    }

    public function getState(): ?State
    {
        return $this->state;
    }

    public function setState(?State $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getTotalPrice()
    {
        return $this->totalPrice;
    }

    public function setTotalPrice($totalPrice): self
    {
        $this->totalPrice = $totalPrice;

        return $this;
    }

}

src/Entity/Time.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TimeRepository")
 */
class Time
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hour_command;

    /**
     * @ORM\Column(type="integer")
     */
    private $value;

    /**
     * @ORM\Column(type="boolean")
     */
    private $midi;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHourCommand(): ?string
    {
        return $this->hour_command;
    }

    public function setHourCommand(string $hour_command): self
    {
        $this->hour_command = $hour_command;

        return $this;
    }

    public function __toString()
    {
        return $this->getHourCommand();
    }

    public function getValue(): ?int
    {
        return $this->value;
    }

    public function setValue(int $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getMidi(): ?bool
    {
        return $this->midi;
    }

    public function setMidi(bool $midi): self
    {
        $this->midi = $midi;

        return $this;
    }

}

src/Form/CommandType.php
<?php

namespace App\Form;

use App\Entity\Command;
use App\Entity\State;
use App\Entity\Time;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('state', EntityType::class, array(
                "class" => State::class
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Command::class,
        ]);
    }
}

src/Controller/CommandController.php
<?php

namespace App\Controller;

use App\Entity\State;
use App\Event\StateCommandEvent;
use App\Repository\CommandmenuRepository;
use App\Repository\StateRepository;
use App\Repository\TimeRepository;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use App\Entity\Command;
use App\Form\CommandType;
use App\Repository\CommandRepository;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/command", host="admin.ojbento.fr")
 */
class CommandController extends AbstractController
{
    protected $dispatcher;
    public function __construct(EventDispatcherInterface $dispatcher)
    {
        $this->dispatcher = $dispatcher;
    }
    /**
     * @Route("/", name="command_index", methods={"GET"})
     */
    public function index(CommandRepository $commandRepository, TimeRepository $timeRepository): Response
    {
        $currentUser = $this->getUser();
        $uniqueKey = $this->generateUniqueKey();
        $currentUser->setApikey($uniqueKey);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($currentUser);
        $entityManager->flush();
        return $this->render('command/index.html.twig', [
            'commands' => $commandRepository->findAll(),
            'count' => 0,
            'api_key' => $uniqueKey,
            'times' => $timeRepository->findAll(),
            'count2' => 0
        ]);
    }

    /**
     * @Route("/{id}/status", name="command_patch", methods={"PATCH"})
     */
    public function patchCommandStatus(Request $request, Command $command, StateRepository $stateRepository): Response
    {
        $apikey = $request->get('apikey');
        $user = $this->getUser();
        if ($apikey == $user->getApikey()) {
            if ($command){
                $form = $this->createForm(CommandType::class, $command);
                $form->submit($request->request->all(), false);
                $em = $this->getDoctrine()->getManager();
                $stateId = $request->get('state');
                $state = $stateRepository->findOneBy(array("value" => $stateId));
                $command->setState($state);
                $CommandEvent = new StateCommandEvent($this->getUser());
                if ($state->getValue() == State::STATUS_ACCEPTED){
                    $this->dispatcher->dispatch('command.accepted', $CommandEvent);
                }
                if ($state->getValue() == State::STATUS_REFUSED){
                    $this->dispatcher->dispatch('command.denied', $CommandEvent);
                }
                if ($state->getValue() == State::STATUS_FINISHED) {
                    $this->dispatcher->dispatch('command.ready', $CommandEvent);

                }
                $em->persist($command);
                $em->flush();
                return new JsonResponse([ 'status' => 'success'],202);
            }
        }
        return new JsonResponse([],403);
    }


    /**
     * @Route("/new", name="command_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $command = new Command();
        $currentUser = $this->getUser();
        $command->setUser($currentUser);
        $form = $this->createForm(CommandType::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($command);
            $entityManager->flush();

            return $this->redirectToRoute('command_index');
        }
        return $this->render('command/new.html.twig', [
            'command' => $command,
            'form' => $form->createView(),

        ]);
    }

    /**
     * @Route("/{id}", name="command_show", methods={"GET"})
     */
    public function show(Command $command): Response
    {
        return $this->render('command/show.html.twig', [
            'command' => $command,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="command_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Command $command): Response
    {
        $form = $this->createForm(CommandType::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('command_index', [
                'id' => $command->getId(),
            ]);
        }

        return $this->render('command/edit.html.twig', [
            'command' => $command,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="command_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Command $command): Response
    {
        if ($this->isCsrfTokenValid('delete'.$command->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($command);
            $entityManager->flush();
        }

        return $this->redirectToRoute('command_index');
    }

    function generateUniqueKey() {
        return sprintf('%s%s', md5(uniqid()),sha1(uniqid()));
    }
}

templates/command/_delete_form.html.twig
<form method="post" action="{{ path('command_delete', {'id': command.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ command.id) }}">
    <button class="btn">Delete</button>
</form>

templates/command/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Command{% endblock %}

{% block body %}
    <h1>Edit Command</h1>

    {{ include('command/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('command_index') }}">back to list</a>

    {{ include('command/_delete_form.html.twig') }}
{% endblock %}

templates/command/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Command index{% endblock %}
{% for command in commands %}
    {% if (command.state.value==1) %}
        {% set count = count + 1 %}
    {% endif %}
    {%  if (command.state.value==2) %}
        {% set count2 = count2 + 1 %}
    {% endif %}
{% endfor %}
{% block body %}
    <button class="refresh float-right btn btn-warning">Refresh</button>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <div class="d-flex">
                    <div class="d-flex">
                        <h2 class="ml-3">{{ count }} Commandes en attente</h2>
                        <select id="pending_select" class="form-group">
                            <option value="all"> Tout lister</option>
                            {% for time in times %}
                                <option class="pending-option-time" data-time="{{ time.value }}" value="{{ time.value }}">
                                    {{ time.hourCommand }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                {% for command in commands %}
                    {% if command.state.value == 1 %}
                    <div class="pending-commands command pending-command-{{ command.time.value }}" data-time="{{ command.time.hourCommand }}" id="command-{{ command.id }}">
                        <div class="header">
                            <div class=" float-right m-2 button-box">
                                <button data-id="{{ command.id }}" data-state-value="2" data-action="accept" class="btn btn-success accept" data-key="{{ api_key }}">Accepter</button>
                                <button data-id="{{ command.id }}" data-state-value="3" data-action="deny" class="btn btn-danger deny" data-key="{{ api_key }}">Refuser</button>
                            </div>
                            <div class="d-flex justify-content-between">
                                <span>Pour <span class="time">{{ command.time.hourCommand }}</span></span>
                                <span> Par
                                    {{ command.user.Fname }}
                                    {{ command.user.Lname }}
                                </span>
                                <span>Tel: {{ command.user.phone }}</span>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div>
                                    Crée le {{ command.datetime | date("j M") }} à  {{ command.datetime | date("H:i") }}
                                </div>
                                <div>
                                    Prix: {{ command.totalPrice }} €
                                </div>
                            </div>
                        </div>
                        <div class="row m-auto w-100">


                        {% if command.commandAssocs%}
                            <div class="col">
                                <div>
                                    <div class="ml-3">A la carte:</div>
                                    {% for assoc in command.commandAssocs %}
                                        <div class="ml-5">{{ assoc.quantity }}x {{ assoc.assoc.quantity }} {{ assoc.assoc.type.name }}s {{ assoc.assoc.product.name }}</div>
                                    {% else %}
                                        <div class="ml-5">Aucun produit à la carte</div>
                                    {%  endfor %}
                                </div>
                            </div>
                        {% endif %}

                        {% if command.commandMenus %}

                            <div class="col">
                                <div>
                                    <div class="ml-3">Menus:</div>
                                    {% for menu in command.commandMenus %}
                                        <div class="ml-5">{{ menu.quantity }} {{ menu.menu.name }}</div>
                                    {% else %}
                                        <div class="ml-5">Aucun menu</div>
                                    {%  endfor %}
                                </div>
                            </div>
                            </div>
                            </div>
                        {% endif %}
                    {%  endif %}
                {% else %}
                    <h3>Pas de commande en attente de validation</h3>
                {% endfor %}
            </div>

            <div class="col-sm-6" id="commandActive">
                <div class="d-flex">
                    <h2>{{ count2 }} Commandes en cours</h2>
                    <select id="accepted_select" class="form-group">
                        <option value="all"> Tout lister</option>
                        {% for time in times %}
                            <option class="accepted-option-time" data-time="{{ time.value }}" value="{{ time.value }}">
                                {{ time.hourCommand }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                {% for command in commands %}
                    {% if command.state.value == 2 %}
                    <div class="accepted-commands command accepted-command-{{ command.time.value }}" data-time="{{ command.time.hourCommand }}" id="command-{{ command.id }}">
                        <div class="header">
                            <div class=" float-right m-2 button-box">
                                <button data-id="{{ command.id }}" data-action="finish" data-state-value="4" class="btn btn-info finish" data-key="{{ api_key }}">Terminé</button>
                            </div>
                            <div class="d-flex justify-content-between">
                                <span>Pour {{ command.time.hourCommand }}</span>
                                <span> Par
                                    {{ command.user.Fname }}
                                    {{ command.user.Lname }}
                                </span>
                                <span>Tel: {{ command.user.phone }}</span>
                            </div>
                            <div class="d-flex justify-content-between">
                                <div>
                                    Crée le {{ command.datetime | date("j M") }} à  {{ command.datetime | date("H:i") }}
                                </div>
                                <div>
                                    Prix: {{ command.totalPrice }} €
                                </div>
                            </div>
                        </div>
                        <div class="row m-auto w-100">


                        {% if command.commandAssocs%}
                            <div class="col">
                                <div>
                                    <div class="ml-3">A la carte:</div>
                                    {% for assoc in command.commandAssocs %}
                                        <div class="ml-5">{{ assoc.quantity }}x {{ assoc.assoc.quantity }} {{ assoc.assoc.type.name }}s {{ assoc.assoc.product.name }}</div>
                                    {% else %}
                                        <div class="ml-5">Aucun produit à la carte</div>
                                    {%  endfor %}
                                </div>
                            </div>
                        {% endif %}

                        {% if command.commandMenus %}

                            <div class="col">
                                <div>
                                    <div class="ml-3">Menus:</div>
                                    {% for menu in command.commandMenus %}
                                        <div class="ml-5">{{ menu.quantity }} {{ menu.menu.name }}</div>
                                    {% else %}
                                        <div class="ml-5">Aucun menu</div>
                                    {%  endfor %}
                                </div>
                            </div>
                            </div>
                            </div>
                        {% endif %}
                    {%  endif %}
                {% else %}
                    <h3>Pas de commande en attente de validation</h3>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script>
        var allpendingCommands = $('.pending-commands');
        var allAcceptedCommands = $('.accepted-commands');
        var pending_times = $('.pending-option-time');
        var accepted_times = $('.accepted-option-time');
        $(document).ready(function() {
            // setTimeout(function(){
            //     location.reload();
            // }, 60000);

            $('.refresh').on('click', function(){
                location.reload();
            });

            $('.accept, .deny, .finish').on('click', function() {
                $(this).prop('disabled', true);
                let stateValue = $(this).attr("data-state-value");
                let commandId = $(this).attr("data-id");
                let action = $(this).attr("data-action");
                let finishButton = '<button data-id="'+commandId+'" data-action="finish" data-state-value="4" class="btn btn-info finish">Terminé</button>';
                let apiKey = $(this).attr('data-key');
                let selectedCommand = $('#command-'+commandId);
                let commandInProcess = $('#commandActive');

                $.ajax({
                    url: 'http://admin.ojbento.fr/command/' + commandId + '/status',
                    type: "PATCH",
                    data: {
                        state: stateValue,
                        apikey : apiKey
                    }
                }).then(function(response) {
                    if (response.status && response.status == "success") {
                        if(action === 'deny' || action === 'finish'){
                            selectedCommand.remove();
                        }
                        else if(action === 'accept'){
                            let buttonBox = $(this).parent();
                            selectedCommand.remove();
                            buttonBox.empty();
                            buttonBox.append(finishButton);
                            commandInProcess.append(selectedCommand);

                        }
                        location.reload();
                    }

                }).catch(function(){
                });

            });
            $('#pending_select').change(function () {
                allpendingCommands.hide();
                let selectedTime = $('#pending_select').val();
                $('.pending-command-'+selectedTime).show();
                if (selectedTime === 'all'){
                    allpendingCommands.show();
                }

            });
            $('#accepted_select').change(function () {
                allAcceptedCommands.hide();
                let selectedTime = $('#accepted_select').val();
                $('.accepted-command-'+selectedTime).show();
                if (selectedTime === 'all'){
                    allAcceptedCommands.show();
                }

            });
            window.onload = function(){
                for (i=0; i<pending_times.length; i++) {
                let pending_time = pending_times[i];
                let accepted_time = accepted_times[i];
                let timeValue = pending_time.attributes[1].value;
                let pendingCommandArray = $('.pending-command-' + timeValue);
                let acceptedCommandArray = $('.accepted-command-' + timeValue);

                let hour = pending_time.innerHTML;
                pending_time.innerHTML = hour + ' - ' + pendingCommandArray.length;
                accepted_time.innerHTML = hour + ' - ' + acceptedCommandArray.length;
            }
            }
        })
    </script>
{% endblock %}

templates/command/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Command{% endblock %}

{% block body %}
    <h1>Create new Command</h1>

    {{ include('command/_form.html.twig') }}

    <a href="{{ path('command_index') }}">back to list</a>
{% endblock %}

templates/command/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Command{% endblock %}

{% block body %}
    <h1>Command</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ command.id }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('command_index') }}">back to list</a>

    <a href="{{ path('command_edit', {'id': command.id}) }}">edit</a>

    {{ include('command/_delete_form.html.twig') }}
{% endblock %}